magephp:
    environments:
        production:
            user: app
            branch: test
            from: ./
            host_path: /var/www/test
            releases: 4
            exclude:
                - vendor
                - app/cache
                - app/log
                - web/app_dev.php
            hosts:
                - webserver1
                - webserver2
                - webserver3
            pre-deploy:
                - git/update
                - composer/install
                - composer/generate-autoload
            on-deploy:
                - symfony/cache-warmup: { env: 'prod' }
                - symfony/assets-install: { env: 'prod' }
                - symfony/assetic-dump: { env: 'prod' }
            on-release:
            post-release:
            post-deploy:
                - magic
    custom_tasks_directory: src/App/Deployment
    custom_tasks:
        - App\Deployment\MagicTask
